
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run start

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on: []
    env_file:
      - ./backend/.env
