
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - neo4j

  neo4j:
      image: neo4j:4.4-community
      environment:
        - NEO4J_AUTH=neo4j/test  # Benutzer: neo4j, Passwort: test
      ports:
        - "7474:7474"  # Neo4j Browser (HTTP)
        - "7687:7687"  # Bolt-Protokoll
      volumes:
        - ./neo4j_data:/data  # <-- Datenbank direkt im Projektordner
